
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { SessionProvider } from "next-auth/react";
import { useState, useEffect, Suspense, lazy } from "react";
import Script from "next/script";
import { useRouter } from "next/router";
import { IntlProvider } from "react-intl";
import translations from "@/locales/translations";
import PushNotification from "@/components/push-notification";
import UploadProgress from "@/components/upload-progress";
import AgeVerification from "@/components/age-verification";
import CommentSection from "@/components/comment-section";
import LikeButton from "@/components/like-button";
import VideoFilter from "@/components/video-filter";
import CaptchaVerification from "@/components/captcha-verification";
import ScrollToTop from "@/components/scroll-to-top";
import LoadingIndicator from "@/components/loading-indicator";
import CreatorDashboard from "@/components/creator-dashboard";
import CreatorRegistration from "@/components/creator-registration";
import Monetization from "@/components/monetization";
import Notifications from "@/components/notifications";
import AnalyticsDashboard from "@/components/analytics-dashboard";
import ContentModeration from "@/components/content-moderation";
import PremiumSubscription from "@/components/premium-subscription";
import LiveStreaming from "@/components/live-streaming";
import SuperChat from "@/components/super-chat";
import NFTVideoOwnership from "@/components/nft-video-ownership";
import VideoPlaylist from "@/components/video-playlist";
import ReferralSystem from "@/components/referral-system";
import CommunityForum from "@/components/community-forum";
import SeoOptimization from "@/components/seo-optimization";
import PremiumDownload from "@/components/premium-download";
import TwoFactorAuth from "@/components/two-factor-auth";
import SecurityCaptcha from "@/components/security-captcha";
import BadgeSystem from "@/components/badge-system";
import EmailNotifications from "@/components/email-notifications";
import PaidAds from "@/components/paid-ads";
import SubscriptionPlans from "@/components/subscription-plans";
import RateLimiting from "@/components/rate-limiting";
import PaymentGateway from "@/components/payment-gateway";
import WalletSystem from "@/components/wallet-system";
import RevenueAnalytics from "@/components/revenue-analytics";
import PayPerView from "@/components/pay-per-view";
import MultiCurrencySupport from "@/components/multi-currency-support";
import PayoutSystem from "@/components/payout-system";
import TransactionHistory from "@/components/transaction-history";
import SecurePayments from "@/components/secure-payments";
import RefundSystem from "@/components/refund-system";
import AutoRenewSubscription from "@/components/auto-renew-subscription";
import EscrowSystem from "@/components/escrow-system";
import FraudDetection from "@/components/fraud-detection";
import SplitPayments from "@/components/split-payments";
import GiftCards from "@/components/gift-cards";
import DynamicPricing from "@/components/dynamic-pricing";
import Crowdfunding from "@/components/crowdfunding";
import DDoSProtection from "@/components/ddos-protection";
import EncryptionModule from "@/components/encryption-module";
import SessionTimeout from "@/components/session-timeout";
import SecurityMonitoring from "@/components/security-monitoring";
import BackupRecovery from "@/components/backup-recovery";
import AIRecommendations from "@/components/ai-recommendations";
import Gamification from "@/components/gamification";
import PersonalizedNotifications from "@/components/personalized-notifications";
import AffiliateSystem from "@/components/affiliate-system";
import SponsoredContent from "@/components/sponsored-content";
import NFTMarketplace from "@/components/nft-marketplace";
import AIContentModeration from "@/components/ai-content-moderation";
import UserRankingSystem from "@/components/user-ranking-system";
import AutoGeneratedCaptions from "@/components/auto-generated-captions";
import InAppMessaging from "@/components/in-app-messaging";
import GeoContentRecommendation from "@/components/geo-content-recommendation";
import AIThumbnailGenerator from "@/components/ai-thumbnail-generator";
import InteractiveLiveStreaming from "@/components/interactive-live-streaming";
import CustomBranding from "@/components/custom-branding";
import CryptoPayments from "@/components/crypto-payments";
import AdSenseOptimization from "@/components/adsense-optimization";
import CopyrightProtection from "@/components/copyright-protection";
import DRMSystem from "@/components/drm-system";
import DMCARegistration from "@/components/dmca-registration";
import Watermarking from "@/components/watermarking";
import VideoUploadEnhancements from "@/components/video-upload-enhancements";
import AdaptiveStreaming from "@/components/adaptive-streaming";
import MultiLanguageSupport from "@/components/multi-language-support";
import SmartPaywall from "@/components/smart-paywall";
import AuctionSystem from "@/components/auction-system";
import VideoQualitySelector from "@/components/video-quality-selector";
import DynamicBitrate from "@/components/dynamic-bitrate";
import VideoCompression from "@/components/video-compression";
import TranscodingBackend from "@/components/transcoding-backend";

const TrendingVideos = lazy(() => import("@/components/trending-videos"));

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const [darkMode, setDarkMode] = useState(false);
  const [isVerified, setIsVerified] = useState(false);
  const [isCreator, setIsCreator] = useState(false);
  const router = useRouter();
  const { locale } = router;

  useEffect(() => {
    const prefersDark = window.matchMedia("(prefers-color-scheme: dark)").matches;
    setDarkMode(prefersDark);
  }, []);

  return (
    <SessionProvider>
      <IntlProvider locale={locale} messages={translations[locale] || translations["en"]}>
        <html lang={locale} className={darkMode ? "dark" : "light"}>
          <head>
            <title>Ms_bee01 - Platform Iklan & Video</title>
            <meta name="description" content="Ms_bee01 adalah platform untuk menampilkan iklan dan mengunggah video pribadi Anda." />
          </head>
          <body className="layout-container">
            <Header setDarkMode={setDarkMode} />
            <AdSenseOptimization />
            <CopyrightProtection />
            <DRMSystem />
            <DMCARegistration />
            <Watermarking />
            <SmartPaywall />
            <AuctionSystem />
            <AdaptiveStreaming />
            <MultiLanguageSupport />
            <VideoQualitySelector />
            <DynamicBitrate />
            <VideoCompression />
            <TranscodingBackend />
            <main className="content">{children}</main>
            <Footer />
          </body>
        </html>
      </IntlProvider>
    </SessionProvider>
  );
}
    